<?php

function markets_list_menu() {
  $items['_load_items'] = array(
    'title' => 'Load Market List',
    'page callback' => 'markets_list_load',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function markets_list_load() {
  $infos = markets_list_get_infos();
  foreach ($infos as $info){
    markets_list_create_node($info);
  };
  // $node = node_load(1);
  // dsm($node);
  return "hello";

}

function markets_list_create_node($info){
  global $user;
  $node = new stdClass();
  $node->title = $info["title"];
  $node->type = $info["type"];
  node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
  $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
  $node->uid = $user->uid;
  $node->status = 1; //(1 or 0): published or not
  // Term reference (taxonomy) field
  $node->field_address[$node->language][0]['value'] = $info["address"];
  $node->field_city[$node->language][0]['value'] = $info["city"];
  $node->field_contact_name[$node->language][0]['value'] = $info["contact name"];
  $node->field_e_mail[$node->language][0]['value'] = $info["email"];
  $node->field_phone[$node->language][0]['value'] = $info["phone"];
  $node->field_postal_code[$node->language][0]['value'] = $info["postal code"];
  $node->field_start_and_end_dates[$node->language][0]['value'] = $info["start date"];
  $node->field_start_and_end_dates[$node->language][0]['value2'] = $info["end date"];
  $node->field_website[$node->language][0]['value'] = $info["website"];
  $node->field_latitude_[$node->language][0]['value'] = $info["latitude"];
  $node->field_longitude[$node->language][0]['value'] = $info["longitude"];
  // Entity reference field
  // 'node' is default,
  // Other possible values are "user" and  "taxonomy_term" 
  $node = node_submit($node); // Prepare node for saving
  node_save($node);
  //drupal_set_message( "Node with nid " . $node->nid . " saved!\n");
}

function markets_list_get_infos(){
  $infos = array(
    array (
      "title" => "Apple Tree Markets",
      "type" => "market",
      "address" => "Davisville Ave and Mount Pleasant",
      "city" => "Toronto",
      "contact name" => "Lesley Stoyan",
      "email" => "appletreemarkets@gmail.com",
      "phone" => "416-899-1990",
      "postal code" => "M4S",
      "start date" => "2014-05-14 00:00:00",
      "end date" => "2014-10-08 00:00:00",
      "website" => "www.appletreemarkets.ca",
    ),

    array (
      "title" => "Bloor Borden MyMarket",
      "type" => "market",
      "address" => "Lippincott Street, Green P Carpark In the heart of Toronto's Annex Neighbourhood",
      "city" => "Toronto",
      "contact name" => "Diana Gonzalez",
      "email" => "diana.mymarket@gmail.com",
      "phone" => "647-848-1497",
      "postal code" => "M2K",
      "start date" => "2014-06-06 00:00:00",
      "end date" => "2014-10-17 00:00:00",
      "website" => "www.my-market.ca",
    ), 

    array (
      "title" => "Dufferin Grove Organic Farmers' Market",
      "type" => "market",
      "address" => "Dufferin Grove Park, 873 Dufferin St., Toronto (south of Bloor, east side of Dufferin)",
      "city" => "Toronto",
      "contact name" => "Anne Freeman",
      "email" => "market@dufferinpark.ca",
      "phone" => "416-392-0913",
      "postal code" => "M6H",
      "start date" => "2014-01-02 00:00:00",
      "end date" => "2014-12-18 00:00:00",
      "website" => "www.dufferinpark.ca",
    ),  

    array (
      "title" => "East Lynn Park MyMarket",
      "type" => "market",
      "address" => "East Lynn Park on Danforth Ave. E. between Coxwell and Woodbine",
      "city" => "Toronto",
      "contact name" => "Diana Gonzalez",
      "email" => "diana.mymarket@gmail.com",
      "phone" => "647-898-1492",
      "postal code" => "",
      "start date" => "2014-06-05 00:00:00",
      "end date" => "2014-08-16 00:00:00",
      "website" => "www.my-market.ca",
    ),  

    array (
      "title" => "East York Farmers' Market",
      "type" => "market",
      "address" => "Located in front of the East York Civic Centre in the park at 850 Coxwel",
      "city" => "Toronto",
      "contact name" => "Ruth Abbott",
      "email" => "rabbott@sympatico.ca",
      "phone" => "416-429-9684",
      "postal code" => "",
      "start date" => "2014-05-13 00:00:00",
      "end date" => "2014-10-28 00:00:00",
      "website" => "",
    ), 

    array (
      "title" => "Evergreen Brick Works Farmers' Market",
      "type" => "market",
      "address" => "550 Bayview Avenue, north end under BLDG 13 Pavillion",
      "city" => "Toronto",
      "contact name" => "Marina Queirolo",
      "email" => "mqueirolo@evergreen.ca",
      "phone" => "416-596-1495 - 231",
      "postal code" => "",
      "start date" => "2014-05-05 00:00:00",
      "end date" => "2014-12-13 00:00:00",
      "website" => "http://ebw.evergreen.ca/farmers-market",
    ),   


    array (
      "title" => "Liberty Village MyMarket",
      "type" => "market",
      "address" => "Located just north of the CNE, Dufferin Gates, Liberty & Hannah Streets. Green P lot",
      "city" => "Toronto",
      "contact name" => "Diana Gonzalez",
      "email" => "diana.mymarket@gmail.com",
      "phone" => "647-898-1492",
      "postal code" => "M5E1C4",
      "start date" => "2014-06-01 00:00:00",
      "end date" => "2014-11-27 00:00:00",
      "website" => "www.my-market.ca",
    ),

   

     array (
      "title" => "Sorauren Farmers' Market",
      "type" => "market",
      "address" => "289 Sorauren Ave",
      "city" => "Toronto",
      "contact name" => "Corry Ouellette",
      "email" => "info@westendfood.coop",
      "phone" => "416-533-6363",
      "postal code" => "M6R1N2",
      "start date" => "2014-01-01 00:00:00",
      "end date" => "2014-12-31 00:00:00",
      "website" => "http://www.westendfood.coop/",
    ),

      

     array (
      "title" => "MyMarket at Concord CityPlace",
      "type" => "market",
      "address" => "Canoe Landing Park Spadina Ave & Front Street",
      "city" => "Toronto",
      "contact name" => "Diana Gonzalez",
      "email" => "diana.mymarket@gmail.com",
      "phone" => "647-898-1492",
      "postal code" => "M5V3Y2",
      "start date" => "2014-06-03 00:00:00",
      "end date" => "2014-10-15 00:00:00",
      "website" => "www.my-market.ca",
    ), 
    
     array (
      "title" => "MyMarket Concord ParkPlace",
      "type" => "market",
      "address" => "Bessarion Road & Sheppard Avenue",
      "city" => "Toronto",
      "contact name" => "Diana Gonzalez",
      "email" => "diana.mymarket@gmail.com",
      "phone" => "647-898-1492",
      "postal code" => "M2K",
      "start date" => "2014-06-06 00:00:00",
      "end date" => "2014-10-17 00:00:00",
      "website" => "www.my-market.ca",
    ), 

      array (
      "title" => "St. Lawrence",
      "type" => "market",
      "address" => "92 Front Street East",
      "city" => "Toronto",
      "contact name" => "Nick Simos",
      "email" => "nsimos@toronto.ca",
      "phone" => "416-392-7120",
      "postal code" => "M5E1C4",
      "start date" => "2014-01-01 00:00:00",
      "end date" => "2014-12-31 00:00:00",
      "website" => "www.stlawrencemarket.com",
    ),
     
      array (
      "title" => "The Leslieville Farmers' Market",
      "type" => "market",
      "address" => "20 Woodward Ave",
      "city" => "Toronto",
      "contact name" => "Daniel Taylor",
      "email" => " daniel@leslievillemarket.com",
      "phone" => "416-219-1453",
      "postal code" => " M4L1A7",
      "start date" => "2014-05-25 00:00:00",
      "end date" => "2014-10-26 00:00:00",
      "website" => "www.my-market.ca",
    ),


  );
  return $infos;
}



